name: Terraform validation
on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: run terraform validation
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform